#`version: "3.5"` указывает версию формата файла Docker Compose, который будет использоваться. В данном случае это версия 3.5. Эта версия поддерживает такие возможности, как объекты `config`, `секреты` и опции `deploy` для развертывания сервисов в рое.
version: "3.5"

#Это определение сети под названием "docker_lasp" с именем сети по умолчанию. Эта сеть может использоваться для соединения различных служб, определенных в файле Docker Compose, позволяя им взаимодействовать друг с другом.
networks:
  docker_lasp:
    name: $DEFAULT_NETWORK

services:
  #`zabbix-java-gateway:` - это служба, определенная в файле Docker Compose. Он развертывает контейнер, в котором запущен Java-шлюз Zabbix, являющийся компонентом системы мониторинга Zabbix. Контейнер настроен с учетом ограничений и резервирования ресурсов, переменных окружения, меток и сетевых настроек. Он открывает порт 10052 и настроен на постоянный перезапуск.
  zabbix-java-gateway:
    #Установка ограничений и резервирования ресурсов для службы zabbix-java-gateway. В частности, он ограничивает использование ЦП до 0,50 и памяти до 512 МБ, а также резервирует для службы минимум 0,25 ЦП и 256 МБ памяти. Это гарантирует, что служба не будет потреблять слишком много ресурсов и влиять на производительность других служб, работающих на той же машине.
    deploy:
      resources:
        #Установка ограничений на ресурсы для службы zabbix-java-gateway в файле Docker Compose. В частности, он ограничивает использование процессора до 0,50 и памяти до 512 МБ.
        limits:
          cpus: "0.50"
          memory: "512M"
        # Секция `reservations` в файле Docker Compose устанавливает минимальные гарантии ресурсов для службы `zabbix-java-gateway`. В частности, он резервирует для службы минимум 0,25 CPU и 256MB памяти. Это означает, что даже при интенсивном использовании ресурсов служба всегда будет иметь в своем распоряжении минимум этих минимальных ресурсов.
        reservations:
          cpus: "0.25"
          memory: "256M"
    #`env_file: - "zabbix.env"` указывает путь к файлу окружения с именем "zabbix.env". Этот файл содержит переменные окружения, которые будут установлены в контейнере, запускающем службу zabbix-java-gateway. Переменные могут быть использованы для настройки поведения службы или для предоставления конфиденциальной информации, такой как пароли или ключи API.
    env_file:
      - "zabbix.env"
    #`image: zabbix/zabbix-java-gateway` указывает образ Docker, который будет использоваться для создания контейнера для службы `zabbix-java-gateway`. Образ берется из реестра Docker Hub и содержит необходимое программное обеспечение и зависимости для запуска компонента Zabbix Java Gateway.
    image: zabbix/zabbix-java-gateway
    # Секция `labels` в файле Docker Compose устанавливает метки метаданных для службы `zabbix-java-gateway`. Эти метки предоставляют дополнительную информацию о службе, такую как ее описание, компания, компонент и операционная система. Эта информация может быть использована в организационных или информационных целях, и доступ к ней можно получить через API Docker или CLI.
    labels:
      - "com.zabbix.description=Zabbix Java Gateway"
      - "com.zabbix.company=Zabbix LLC"
      - "com.zabbix.component=java-gateway"
      - "com.zabbix.os=linux"
    # Секция `ports` в файле Docker Compose открывает порт 10052 контейнера, в котором запущен сервис `zabbix-java-gateway`, для хост-машины. Точнее, он отображает порт 10052 контейнера на порт 10052 хост-машины, позволяя внешним системам взаимодействовать с компонентом Zabbix Java Gateway через этот порт.
    ports:
      - "10052:10052"
    #`restart: always` - это параметр конфигурации в файле Docker Compose, который указывает, что контейнер для сервиса должен всегда перезапускаться, если он останавливается по какой-либо причине, например, из-за сбоя или ручной остановки. Это гарантирует, что служба всегда работает и доступна, даже в случае неожиданных сбоев.
    restart: always
    #`container_name: zabbix-java-gateway` задает пользовательское имя для контейнера, который будет создан для службы `zabbix-java-gateway`. Это позволяет легко идентифицировать контейнер и управлять им, используя это имя вместо случайно сгенерированного имени.
    container_name: zabbix-java-gateway
    #`networks: - "docker_net"` определяет сеть, к которой будут подключены службы в файле Docker Compose. В данном случае сеть называется "docker_net" и создается как внутренняя сеть внутри Docker. Это позволяет службам общаться друг с другом, используя имена своих контейнеров в качестве имен хостов, не открывая свои порты для внешней сети.
    networks:
      - "docker_net"
